### ISSUE TITLE
Training on this T-CNN

### ISSUE THREAD

**Issue by TedaLIEz** [ruihou/caffe-3d#1]
I'm interested in this T-CNN and I want to reproduce your experiments, but I haven't found the instructions about the training process. Are there any docs for this?

**Comment by eglxiang** [comment]
Yes, want to know. or is there pytorch version?

**Comment by bit-scientist** [comment]
I am interested too. I wonder how many people are required to get his attention and jot down instructions or implementation details.

**Comment by helq2612** [comment]
Me too. But seems no implementation has been released from the authors.

**Comment by ruihou** [comment]
This Repo is not the implementation of T-CNN
